"""The LAMMPS engine: deck rendering first, execution second.

Rendering is separated from running on purpose. The exact ``pair_style`` and
``pair_coeff`` strings -- and the whole input deck around them -- are what a
LAMMPS run actually *is*, so :func:`render_deck` is pure, testable, and
callable on a machine with no LAMMPS at all. ``mlip validate`` renders the
deck it would submit; ``mlip_manifest.json`` stores it verbatim.

Execution then has two routes, in order of preference:

* the LAMMPS Python module, which can hand back forces and per-atom energies
  directly from memory;
* an ``lmp`` executable, driven through a written deck plus a dump file.

Units: LAMMPS ``metal`` already speaks eV and Angstrom, but ``real`` does not,
and LAMMPS reports *pressure* in bars where this subsystem's canonical stress
is eV/Angstrom^3 with the opposite sign. Both conversions happen in
:func:`stress_from_pressure`, never implicitly.
"""
from __future__ import annotations

import contextlib
import os
import subprocess
import time
from pathlib import Path

from ..capabilities import CapabilitySet
from ..environment import Availability, executable_available, module_available
from ..errors import MissingDependencyError, MlipError
from ..specs import LammpsMlipPotentialSpec, SimulationSpec
from ..units import EV_PER_ANGSTROM3_IN_BAR, LAMMPS_METAL, lammps_unit_system
from .base import EngineRuntime

DATA_FILE = "structure.lmp"
DECK_FILE = "in.lammps"
DUMP_FILE = "forces.dump"
THERMO_FILE = "thermo_result.txt"
TRAJECTORY_FILE = "smoke_md.lammpstrj"
LOG_FILE = "log.lammps"

#: LAMMPS timestep units per unit style. ``metal`` counts picoseconds, ``real``
#: femtoseconds; getting this wrong is a factor of 1000 in the dynamics.
TIMESTEP_PER_FS = {"metal": 1e-3, "real": 1.0}
#: Thermostat/barostat damping is quoted in the same time unit as the timestep.
DAMPING_PER_FS = TIMESTEP_PER_FS

THERMO_KEYS = ("pe", "ke", "etotal", "temp", "press", "pxx", "pyy", "pzz", "pyz", "pxz", "pxy")


class LammpsEngine(EngineRuntime):
    kind = "lammps"
    requires = ()
    native_units = LAMMPS_METAL.name

    def capabilities(self) -> CapabilitySet:
        """LAMMPS carries everything; whether a pair style supplies it is separate."""
        return CapabilitySet(
            energy=True,
            forces=True,
            stress=True,
            per_atom_energy=True,
            periodic=True,
            # Not yet honoured by the rendered deck (one boundary style for all
            # axes; no frozen-atom groups), so such jobs are refused at validate.
            partial_periodic=False,
            fixed_atoms=False,
            gpu=True,
            elements=None,
            precisions=None,
            engines=frozenset({"lammps"}),
            native_units=self.native_units,
            notes=(
                "LAMMPS reports pressure in bars; this subsystem converts to "
                "eV/Angstrom^3 stress with the sign flipped",
            ),
        )

    def availability(self) -> Availability:
        if module_available("lammps"):
            return Availability(True, (), "LAMMPS python module")
        executable = self.spec.executable or "lmp"
        if executable_available(executable):
            return Availability(True, (), f"{executable} executable")
        return Availability(
            False,
            ("lammps",),
            "neither the LAMMPS python module nor an 'lmp' executable was found",
        )


# ---------------------------------------------------------------------------
# Deck rendering (pure; no LAMMPS required)
# ---------------------------------------------------------------------------


def render_deck(
    potential: LammpsMlipPotentialSpec,
    simulation: SimulationSpec,
    *,
    n_types: int,
    periodic: bool = True,
    data_file: str = DATA_FILE,
    dump_file: str = DUMP_FILE,
    thermo_file: str = THERMO_FILE,
    trajectory_file: str = TRAJECTORY_FILE,
    thermo_interval: int | None = None,
) -> tuple[str, ...]:
    """Render the complete input deck as an ordered tuple of commands.

    Pure: no files are written and no LAMMPS is needed. The pair commands come
    from :meth:`LammpsMlipPotentialSpec.render_pair_commands`, so what is
    validated, what is stored in the manifest and what is executed are the
    same strings.
    """
    if n_types != len(potential.type_map):
        raise ValueError(
            f"deck asks for {n_types} atom types but the potential maps "
            f"{len(potential.type_map)}"
        )
    boundary = "p p p" if periodic else "f f f"
    lines = [
        f"# generated by nio-md-prep mlip ({potential.label})",
        "clear",
        f"units {potential.units}",
        f"atom_style {potential.atom_style}",
        f"boundary {boundary}",
        "atom_modify map yes",
        "box tilt large",
    ]
    if potential.newton:
        lines.insert(2, f"newton {potential.newton}")
    lines.append(f"read_data {data_file}")
    lines.extend(potential.render_pair_commands())
    lines.append("")
    lines.append("compute mlip_pe_atom all pe/atom")
    lines.append("thermo_style custom step " + " ".join(THERMO_KEYS))

    if simulation.task == "md":
        lines.extend(
            _md_block(
                potential,
                simulation,
                trajectory_file=trajectory_file,
                dump_file=dump_file,
                thermo_interval=thermo_interval,
            )
        )
    else:
        lines.extend(
            [
                "thermo 1",
                f"dump mlip_forces all custom 1 {dump_file} id type x y z fx fy fz c_mlip_pe_atom",
                "dump_modify mlip_forces sort id",
                "run 0",
            ]
        )
    lines.extend(_thermo_dump_block(thermo_file))
    return tuple(lines)


def _md_block(
    potential: LammpsMlipPotentialSpec,
    simulation: SimulationSpec,
    *,
    trajectory_file: str,
    dump_file: str,
    thermo_interval: int | None,
) -> list[str]:
    timestep = simulation.timestep_fs * TIMESTEP_PER_FS[potential.units]
    # Defaults resolve through the one shared constant (specs.DEFAULT_*_DAMPING_FS).
    damping = simulation.resolved_thermostat_damping_fs * DAMPING_PER_FS[potential.units]
    barostat_damping = simulation.resolved_barostat_damping_fs * DAMPING_PER_FS[potential.units]
    interval = thermo_interval or max(1, simulation.log_interval)
    lines = [f"timestep {timestep:.10g}"]
    if simulation.temperature_K:
        seed = simulation.seed if simulation.seed is not None else 12345
        lines.append(
            f"velocity all create {simulation.temperature_K:.6g} {seed} "
            "mom yes rot yes dist gaussian"
        )
    temperature = simulation.temperature_K
    if simulation.ensemble == "nve":
        lines.append("fix mlip_integrate all nve")
    elif simulation.ensemble == "nvt":
        lines.append(
            f"fix mlip_integrate all nvt temp {temperature:.6g} {temperature:.6g} "
            f"{damping:.10g}"
        )
    elif simulation.ensemble == "npt":
        pressure = simulation.pressure_bar
        lines.append(
            f"fix mlip_integrate all npt temp {temperature:.6g} {temperature:.6g} "
            f"{damping:.10g} iso {pressure:.6g} {pressure:.6g} {barostat_damping:.10g}"
        )
    lines.extend(
        [
            f"thermo {interval}",
            f"dump mlip_traj all custom {max(1, simulation.trajectory_interval)} "
            f"{trajectory_file} id type x y z",
            "dump_modify mlip_traj sort id",
            f"run {simulation.steps}",
            f"write_dump all custom {dump_file} id type x y z fx fy fz c_mlip_pe_atom "
            "modify sort id",
        ]
    )
    return lines


def _thermo_dump_block(thermo_file: str) -> list[str]:
    """Print the thermo quantities this subsystem reads back, one per line.

    Used by the executable route, which has no way to reach into LAMMPS's
    memory. Harmless under the Python route.
    """
    lines = []
    for index, key in enumerate(THERMO_KEYS):
        lines.append(f"variable mlip_{key} equal {key}")
        redirect = "file" if index == 0 else "append"
        lines.append(f'print "{key} ${{mlip_{key}}}" {redirect} {thermo_file}')
    return lines


def write_data_file(atoms, potential: LammpsMlipPotentialSpec, path: Path) -> Path:
    """Write the structure as a LAMMPS data file in the potential's type order.

    ``specorder`` is taken from ``potential.type_map``, which is what makes the
    ``pair_coeff`` element list and the data file agree. Without it, LAMMPS
    would assign types by order of appearance and silently mislabel elements.
    """
    from ase.io import write as ase_write

    from ..structures import to_lammps_type_order

    to_lammps_type_order(atoms, potential.type_map)  # validates coverage first
    specorder = [potential.type_map[t] for t in sorted(potential.type_map)]
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    ase_write(
        str(path),
        atoms,
        format="lammps-data",
        specorder=specorder,
        atom_style=potential.atom_style,
        masses=True,
    )
    return path


# ---------------------------------------------------------------------------
# Execution
# ---------------------------------------------------------------------------


def run_deck(
    commands,
    *,
    workdir: Path,
    engine_spec=None,
    n_atoms: int,
    want_per_atom: bool = False,
) -> dict:
    """Execute a rendered deck and read energy, forces, stress and site energies back.

    Always writes the deck to ``workdir`` first, whichever route runs it, so a
    failed job leaves behind exactly the input that failed.
    """
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)
    deck_path = workdir / DECK_FILE
    deck_path.write_text("\n".join(commands) + "\n", encoding="utf-8")

    if module_available("lammps"):
        return _run_with_module(commands, workdir, n_atoms, want_per_atom, deck_path)
    executable = (engine_spec.executable if engine_spec else None) or "lmp"
    if executable_available(executable):
        return _run_with_executable(executable, workdir, deck_path, want_per_atom)
    raise MissingDependencyError(
        "running a LAMMPS deck",
        ("lammps",),
        hint=(
            f"The rendered deck was written to {deck_path}. Install the LAMMPS python "
            "module, put an 'lmp' executable on PATH, or run that deck yourself."
        ),
    )


def _run_with_module(commands, workdir: Path, n_atoms: int, want_per_atom: bool, deck_path: Path):
    import numpy as np
    from lammps import LMP_STYLE_ATOM, LMP_TYPE_VECTOR, lammps

    started = time.perf_counter()
    # The deck names its data, dump and thermo files relatively, so the run has
    # to happen in the job directory. `shell cd` would break on any path with a
    # space in it, which on Windows is most of them.
    with _working_directory(workdir):
        lmp = lammps(cmdargs=["-log", LOG_FILE, "-screen", "none"])
        try:
            lmp.commands_list(list(commands))
            thermo = {key: float(lmp.get_thermo(key)) for key in THERMO_KEYS}
            ids = np.array(lmp.numpy.extract_atom("id")).flatten()
            order = np.argsort(ids)
            forces = np.array(lmp.numpy.extract_atom("f"))[order]
            per_atom = None
            if want_per_atom:
                values = lmp.numpy.extract_compute(
                    "mlip_pe_atom", LMP_STYLE_ATOM, LMP_TYPE_VECTOR
                )
                per_atom = np.array(values).flatten()[order]
            positions = np.array(lmp.numpy.extract_atom("x"))[order]
        finally:
            lmp.close()
    return {
        "route": "python-module",
        "thermo": thermo,
        "forces": [[float(c) for c in row] for row in forces],
        "per_atom_energy": [float(v) for v in per_atom] if per_atom is not None else None,
        "positions": [[float(c) for c in row] for row in positions],
        "wall_time_s": time.perf_counter() - started,
        "deck_path": str(deck_path),
        "log_path": str(workdir / LOG_FILE),
    }


def _run_with_executable(executable: str, workdir: Path, deck_path: Path, want_per_atom: bool):
    started = time.perf_counter()
    completed = subprocess.run(
        [executable, "-in", deck_path.name, "-log", LOG_FILE],
        cwd=str(workdir),
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        tail = (completed.stderr or completed.stdout or "").strip().splitlines()[-20:]
        raise MlipError(
            f"{executable} exited with status {completed.returncode} for {deck_path}.\n"
            + "\n".join(tail)
        )
    thermo = _read_thermo(workdir / THERMO_FILE)
    forces, per_atom, positions = _read_dump(workdir / DUMP_FILE)
    return {
        "route": "executable",
        "thermo": thermo,
        "forces": forces,
        "per_atom_energy": per_atom if want_per_atom else None,
        "positions": positions,
        "wall_time_s": time.perf_counter() - started,
        "deck_path": str(deck_path),
        "log_path": str(workdir / LOG_FILE),
    }


@contextlib.contextmanager
def _working_directory(path: Path):
    previous = os.getcwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(previous)


def _read_thermo(path: Path) -> dict[str, float]:
    if not path.exists():
        raise MlipError(f"LAMMPS did not write {path}; the run did not reach its thermo block")
    values: dict[str, float] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        parts = line.split()
        if len(parts) == 2:
            try:
                values[parts[0]] = float(parts[1])
            except ValueError:
                continue
    return values


def _read_dump(path: Path):
    """Read the single-snapshot custom dump written by the rendered deck."""
    if not path.exists():
        raise MlipError(f"LAMMPS did not write {path}; forces could not be read back")
    lines = path.read_text(encoding="utf-8").splitlines()
    try:
        header = next(i for i, line in enumerate(lines) if line.startswith("ITEM: ATOMS"))
    except StopIteration:
        raise MlipError(f"{path} contains no ATOMS section") from None
    columns = lines[header].split()[2:]
    index = {name: position for position, name in enumerate(columns)}
    rows = [line.split() for line in lines[header + 1:] if line.strip()]
    rows.sort(key=lambda row: int(row[index["id"]]))
    forces = [[float(row[index[c]]) for c in ("fx", "fy", "fz")] for row in rows]
    positions = [[float(row[index[c]]) for c in ("x", "y", "z")] for row in rows]
    per_atom = (
        [float(row[index["c_mlip_pe_atom"]]) for row in rows]
        if "c_mlip_pe_atom" in index
        else None
    )
    return forces, per_atom, positions


def stress_from_pressure(thermo: dict, units: str) -> list[float] | None:
    """Convert LAMMPS pressure components to a canonical Voigt stress.

    Two conversions, both explicit: LAMMPS reports pressure (``metal``: bars;
    ``real``: atmospheres, which this subsystem does not accept), and pressure
    is the negative of stress under the convention ASE and this subsystem use.
    """
    keys = ("pxx", "pyy", "pzz", "pyz", "pxz", "pxy")
    if not all(key in thermo for key in keys):
        return None
    if units != "metal":
        # Only metal units have a bar-based pressure this subsystem converts.
        return None
    return [-thermo[key] / EV_PER_ANGSTROM3_IN_BAR for key in keys]


def energy_to_eV(value: float, units: str) -> float:
    return value * lammps_unit_system(units).energy_in_eV


def forces_to_eV_per_A(forces, units: str):
    factor = lammps_unit_system(units).force_in_eV_per_angstrom
    return [[component * factor for component in row] for row in forces]


__all__ = [
    "DATA_FILE",
    "DECK_FILE",
    "DUMP_FILE",
    "THERMO_FILE",
    "TRAJECTORY_FILE",
    "LOG_FILE",
    "TIMESTEP_PER_FS",
    "THERMO_KEYS",
    "LammpsEngine",
    "render_deck",
    "write_data_file",
    "run_deck",
    "energy_to_eV",
    "forces_to_eV_per_A",
    "stress_from_pressure",
]
